[package]
name = "gitr"
version = "0.1.0"
authors = ["Josh Gendein <joshua@gendein.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
